# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Create a group of dependencies to be updated together in one pull request
    groups:
       # Specify a name for the group, which will be used in pull request titles
       # and branch names
       grouped-dependencies:
          # Define patterns to include dependencies in the group (based on
          # dependency name)
          patterns:
            - "*"
          # Define patterns to exclude dependencies from the group (based on
          # dependency name)
          #exclude-patterns:
          #  - "FluentAssertions*"
    ignore:
        - dependency-name: "FluentAssertions*"
          # Specify the versioning strategy for this dependency
          versions: [">=8.0.0"]
